# Hard Voting
#   Heterogeneious models used
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import BaggingClassifier,RandomForestClassifier, AdaBoostClassifier

from sklearn.ensemble import VotingClassifier


def VotingClassification():
    border = '*'*40
    #-----------------------------------------------------
    # Step 1 : Load the data set
    #-----------------------------------------------------
    print(border)
    print("Step 1 : Load the data set")
    print(border)
    df = pd.read_csv("Fraudulent_Transaction_Detection.csv")

    print("Shape of dataset:", df.shape)
    print("First 5 records")
    print(df.head())

    #-----------------------------------------------------
    #Step 2 : Check for missing values
    #-----------------------------------------------------
    print(border)
    print("Step 2 : Check for missing values")
    print(border)

    print("Check for missing values")
    print(df.isnull().sum())

    #-----------------------------------------------------
    #Step 3 : Seperate features and labels (Input/Output)
    #-----------------------------------------------------
    print(border)
    print("Step 3 : Seperate features and labels (Input/Output)")
    print(border)

    X = df.drop("Fraud", axis=1)
    Y = df["Fraud"]

    print("X share:", X.shape)
    print("Y share:", Y.shape)

    #-----------------------------------------------------
    # Step 4: Split dataset for training and testing
    #-----------------------------------------------------
    print(border)
    print("Step 4: Split dataset for training and testing")
    print(border)

    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

    # #-----------------------------------------------------
    # # Step 5: Scale the features
    # #-----------------------------------------------------

    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)     #scale the data to maintain in same form 
    X_test = scaler.fit_transform(X_test)   
  
    #-----------------------------------------------------
    # Step 6 :Train Decision Tree
    #-----------------------------------------------------
    print(border)
    print("Step 6 :Train Decision Tree")
    print(border)

    model_det = DecisionTreeClassifier(random_state=42)
    model_det = model_det.fit(X_train,Y_train)
    Y_pred_det = model_det.predict(X_test)

    #-----------------------------------------------------
    # Step 7 :Train Bagging classifier
    #-----------------------------------------------------
    print(border)
    print("Step 7 :Train KNN")
    print(border)

    model_bagging = BaggingClassifier(n_estimators=10, random_state=42)    

    model_bagging = model_bagging.fit(X_train, Y_train)
    Y_pred_BgCls  = model_bagging.predict(X_test)

    #-----------------------------------------------------
    # Step 8 : Train and evaluate the RandomForestClassifier model
    #-----------------------------------------------------
    
    model_randomFrst = RandomForestClassifier(
        n_estimators=10, 
        random_state=42
        )  

    model_randomFrst  = model_randomFrst.fit(X_train, Y_train)
    Y_pred_RndFrst  = model_randomFrst.predict(X_test)

    #-----------------------------------------------------
    # Step 9 : Train and evaluate the AdaBoostClassifier model
    #-----------------------------------------------------
    model_adaBst = AdaBoostClassifier(
        n_estimators=50,
        learning_rate=1.0,
        random_state=42)    

    model_adaBst  = model_adaBst.fit(X_train, Y_train)
    Y_pred_AdaBoost  = model_adaBst.predict(X_test)

    #-----------------------------------------------------
    # Step 10 :Create the voting models
    #-----------------------------------------------------

    model = VotingClassifier(
        estimators=[
            ('decision_tree',model_det),         #model names (logistic) can be any specifire/identifier 
            ('bagging',model_bagging), 
            ('randomF',model_randomFrst),
            ('adb', model_adaBst)
            ], 
        voting="hard"
    )

    model  = model.fit(X_train, Y_train)
    Y_pred_vote  = model.predict(X_test)
    print("Prediction generated by voting: ",Y_pred_vote)

    #-----------------------------------------------------
    # Step 11 : Calculate the individual accuracy of all algorithms
    #-----------------------------------------------------
    print(border)
    print("Step 8 : Calculate the individual accuracy of all three algorithms")
    print(border)

    print("Accuracy of DT: ", accuracy_score(Y_test, Y_pred_det))
    print("Accuracy of BaggingClassifier: ", accuracy_score(Y_test, Y_pred_BgCls))
    print("Accuracy of RandomForestClassifier: ", accuracy_score(Y_test, Y_pred_RndFrst))
    print("Accuracy of AdaBoostClassifier: ", accuracy_score(Y_test, Y_pred_AdaBoost))
    print("Accuracy of VotingClassifier: ", accuracy_score(Y_test, Y_pred_vote))

    #-----------------------------------------------------
    # Step 12 : Calculate the individual precision of all algorithms
    #-----------------------------------------------------
    print("classification_report of DT: \n", classification_report(Y_test, Y_pred_det))
    print("classification_report of BaggingClassifier: \n", classification_report(Y_test, Y_pred_BgCls))
    print("classification_report of RandomForestClassifier: \n", classification_report(Y_test, Y_pred_RndFrst))
    print("classification_report of AdaBoostClassifier: \n", classification_report(Y_test, Y_pred_AdaBoost))
    print("classification_report of VotingClassifier: \n", classification_report(Y_test, Y_pred_vote))

    
def main():
    VotingClassification()


if __name__ == "__main__":
    main()
